"use client";
import { FormEvent, useEffect, useState } from "react";

type Order = { id: string; order_number: string; name: string; email: string; item_summary: string; total: number; status: string; tracking_number?: string };
type Member = { id: string; name: string; email: string; role: "member" | "operator" | "admin"; status: "active" | "suspended"; created_at: string };
const statuses = [["pending", "待確認"], ["making", "製作中"], ["shipped", "已出貨"], ["delivered", "已完成"], ["cancelled", "已取消"]];
const roles = [["member", "一般會員"], ["operator", "訂單管理員"], ["admin", "系統管理員"]];

export default function AdminOrders({ role }: { role: "operator" | "admin" }) {
  const [orders, setOrders] = useState<Order[]>([]);
  const [members, setMembers] = useState<Member[]>([]);
  const [section, setSection] = useState<"orders" | "members">("orders");
  const [notice, setNotice] = useState("");
  const loadOrders = () => fetch("/api/admin/orders").then(r => r.json()).then(d => d.error ? setNotice(d.error) : setOrders(d.orders || []));
  const loadMembers = () => { if (role === "admin") fetch("/api/admin/members").then(r => r.json()).then(d => d.error ? setNotice(d.error) : setMembers(d.members || [])); };
  useEffect(() => { loadOrders(); loadMembers(); }, []);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const response = await fetch("/api/admin/orders", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json(); setNotice(response.ok ? "訂單已建立。" : data.error); if (response.ok) { formElement.reset(); loadOrders(); } };
  const updateOrder = async (order: Order) => { const response = await fetch("/api/admin/orders", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: order.id, status: order.status, trackingNumber: order.tracking_number }) }); const data = await response.json(); setNotice(response.ok ? "訂單已更新。" : data.error); if (response.ok) loadOrders(); };
  const updateMember = async (member: Member) => { const response = await fetch("/api/admin/members", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: member.id, role: member.role, status: member.status }) }); const data = await response.json(); setNotice(response.ok ? "會員權限已更新。" : data.error); if (response.ok) loadMembers(); };
  return <main className="admin-orders"><header><a className="brand" href="/"><img className="brand-logo" src="/hire-logo.png" alt="hire Lab." />hire Lab.</a><div><button className={section === "orders" ? "active" : ""} onClick={() => setSection("orders")}>訂單管理</button>{role === "admin" && <button className={section === "members" ? "active" : ""} onClick={() => setSection("members")}>會員權限</button>}<a href="/member">會員中心</a></div></header><section><p className="eyebrow">STUDIO ADMIN · {role.toUpperCase()}</p><h1>{section === "orders" ? "訂單管理" : "會員權限"}</h1>{notice && <p className="member-notice">{notice}</p>}{section === "orders" ? <><p className="admin-orders-lead">建立訂單並更新製作、出貨與物流狀態。</p><article className="admin-order-create"><h2>建立訂單</h2><form onSubmit={create}><input name="email" type="email" placeholder="會員 Email" required /><input name="itemSummary" placeholder="商品或服務內容" required /><input name="total" type="number" min="0" placeholder="訂單金額" required /><select name="status">{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input name="trackingNumber" placeholder="物流單號（選填）" /><button className="button button-dark">建立訂單</button></form></article><article className="admin-order-table"><h2>全部訂單</h2>{orders.length === 0 ? <p>目前尚未建立訂單。</p> : orders.map(order => <div className="admin-order-row" key={order.id}><div><b>{order.order_number}</b><span>{order.name} · {order.email}</span><small>{order.item_summary} · NT$ {order.total.toLocaleString()}</small></div><select value={order.status} onChange={e => setOrders(orders.map(x => x.id === order.id ? { ...x, status: e.target.value } : x))}>{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input value={order.tracking_number || ""} placeholder="物流單號" onChange={e => setOrders(orders.map(x => x.id === order.id ? { ...x, tracking_number: e.target.value } : x))} /><button onClick={() => updateOrder(order)}>儲存</button></div>)}</article></> : <article className="admin-order-table"><h2>會員與角色</h2>{members.map(member => <div className="admin-member-row" key={member.id}><div><b>{member.name}</b><span>{member.email}</span></div><select value={member.role} onChange={e => setMembers(members.map(x => x.id === member.id ? { ...x, role: e.target.value as Member["role"] } : x))}>{roles.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={member.status} onChange={e => setMembers(members.map(x => x.id === member.id ? { ...x, status: e.target.value as Member["status"] } : x))}><option value="active">啟用</option><option value="suspended">停權</option></select><button onClick={() => updateMember(member)}>儲存權限</button></div>)}</article>}</section></main>;
}
